Edit readme + add simple function
AstroHackWeek/pr_review_tutorial pull request #16
Opened 2019-08-27 08:52 UTC by contardog

blabla

2019-08-27 08:57 UTC, Yoshinta commented
I am going to review this

2019-08-27 09:11 UTC, Yoshinta requested changes
Hi,
I wrote some suggestions in your code.

2019-08-27 09:11 UTC, Yoshinta commented on Contardo/template/simple_functions.py
> +	if numb%2:
this function only check if the input is even.
The command is to return True if the input is prime and False otherwise.
The input must be integer.

2019-08-27 09:11 UTC, Yoshinta commented on Contardo/template/buggy_function.py
> +    decimal :
I don't see any changes in the code. Only the notes.
Try ti check the angles->RA conversion.

2019-08-27 09:11 UTC, Yoshinta commented on Contardo/template/README.md
> +is prime function return true if prime.
Good!
Maybe add examples.

2019-08-28 15:56 UTC, bsipocz commented
@contardog @Yoshinta - Thanks for opening the pull request and for the review(s)! Below I have provided a few comments about the *process* of the pull request and review. Note that we are not conducting a review of the code itself, because the exercise was about the overall process not the details of the code. Also, because there are pending suggestions, we will not merge this PR until the end of Astro Hack Week.

@contardog - it would have been good to provide a description for the PR, even if it duplicates a little the title.

@Yoshinta - you did not select "approve" or "request changes" when you submitted the review.  Without that a maintainer isn't sure if your review should be taken as a complete review or just general comments.

2019-09-10 02:40 UTC, bsipocz commented
As a closure to AstroHackWeek, we go ahead and merge this now. Thank you both.

2019-09-10 02:40 UTC, merged