angle_to_sexigesimal bugfix
AstroHackWeek/pr_review_tutorial pull request #19
Opened 2019-08-27 08:54 UTC by stephenportillo

Fixed degree-to-hour conversion ratio and made HMS printout zero padded

2019-08-27 09:14 UTC, tahumada requested changes
Just trying!

2019-08-27 09:14 UTC, tahumada commented on Portillo/template/buggy_function.py
> +    hours_num = angle_in_degrees*24/360
I'll take a look at it

2019-08-27 09:14 UTC, tahumada commented on Portillo/template/buggy_function.py
> +    hours_num = angle_in_degrees*24/360
It works fine!

2019-08-27 09:15 UTC, tahumada commented
Hey, trying again

2019-08-27 09:15 UTC, stephenportillo commented
Hey, thanks for reviewing my code!

2019-08-27 09:17 UTC, tahumada approved these changes

2019-08-27 09:19 UTC, tahumada commented
@astrofrog  @stephenportillo's code is ready to be merged!

2019-08-28 15:54 UTC, bsipocz commented
@stephenportillo @tahumada - Thanks for opening the pull request and for the review(s)! Everything looks good, so we'll go ahead and merge this. Note that we are not conducting a review of the code itself, because the exercise was about the overall process not the details of the code. 

@tahumada - your comment seems generic and not about the specific code changes in the "Files changed" tab. For these cases it's possible to leave the generic comments when you set the review status (Approve/Require Changes/etc.), or in the conversation tab, here rather than inline.

2019-08-28 15:54 UTC, merged