programme that says if a number is prime
AstroHackWeek/pr_review_tutorial pull request #25
Opened 2019-08-27 08:56 UTC by RubenArjona

2019-08-27 09:02 UTC, atakan commented
I'd like to review this.

2019-08-27 09:10 UTC, atakan requested changes
Generally sound approach. A few suggestions below.

2019-08-27 09:10 UTC, atakan commented on Arjona/template/simple_functions.py
> +# Python program to check if
It would be more useful if this was a function, rather than a standalone program.

2019-08-27 09:10 UTC, atakan commented on Arjona/template/simple_functions.py
> +   for i in range(2, num//2):
Probably sqrt(n) is more useful than n//2.

2019-08-27 09:10 UTC, atakan commented on Arjona/template/simple_functions.py
> +   print(num, "is not a prime number")
If this was a function, these print() statements would need to be changed into returning True or False values.

2019-08-28 14:36 UTC, bsipocz commented
@RubenArjona @atakan - Thanks for opening the pull request and for the review(s)! Below I have provided a few comments about the *process* of the pull request and review. Note that we are not conducting a review of the code itself, because the exercise was about the overall process not the details of the code. Also, because there are pending suggestions, we will not merge this PR until the end of Astro Hack Week.

@RubenArjona - it would have been good to provide a description for the PR, even if it duplicates a little the title.

2019-09-10 02:45 UTC, bsipocz commented
As a closure to AstroHackWeek, we go ahead and merge this now. Thank you both.

2019-09-10 02:45 UTC, merged