Task_day2
AstroHackWeek/pr_review_tutorial pull request #28
Opened 2019-08-27 09:00 UTC by shilpi1958

2019-08-27 09:03 UTC, luis-ahw2019 commented
Hi Shilpi,

I am going to review this pull request.

Cheers,

Luis

2019-08-27 09:07 UTC, luis-ahw2019 requested changes
In line 16 the "n" should be "num".

In line 23 "true" should be "True".

2019-08-27 09:31 UTC, luis-ahw2019 requested changes
The two bugs reported in the preview review have been successfully fixed :-)

Nevertheless, I have just noticed other one. Good opportunity for iterating again :-)

2019-08-27 09:31 UTC, luis-ahw2019 commented on Jain/template/simple_functions.py
> +def is_prime(num)
```suggestion
def is_prime(num):
```

2019-08-27 09:57 UTC, shilpi1958 commented on Jain/template/simple_functions.py
> +def is_prime(num)
Done! Thanks :)

2019-08-27 10:33 UTC, luis-ahw2019 requested changes
Oh, I am sorry by not reporting all the bugs at once, but I have discovered an indentation error now.

2019-08-27 10:33 UTC, luis-ahw2019 commented on Jain/template/simple_functions.py
> +        return False
```suggestion
            return False
```

2019-08-28 15:50 UTC, bsipocz commented
@shilpi1958 @luis-ahw2019 - Thanks for opening the pull request and for the review(s)! Below I have provided a few comments about the *process* of the pull request and review. Note that we are not conducting a review of the code itself, because the exercise was about the overall process not the details of the code. Also, because there are pending suggestions, we will not merge this PR until the end of Astro Hack Week.

@shilpi1958 - it would have been good to provide a description for the PR, and also a title that describes the content of the PR.

@luis-ahw2019 - you've referred to certain lines in your first review. Nice to see the process that later on you've discovered that it's also possible to leave those comments on the affected lines either as a comment or a change suggestion. Another minor thing is, that you did not select "approve" or "request changes" when you submitted the review.  Without that a maintainer isn't sure if your review should be taken as a complete review or just general comments.

2019-09-10 02:45 UTC, bsipocz commented
As a closure to AstroHackWeek, we go ahead and merge this now. Thank you both.

2019-09-10 02:45 UTC, merged