Changes
AstroHackWeek/pr_review_tutorial pull request #37
Opened 2019-08-27 09:15 UTC by astrofrog

My work today. It should be awesome and ready to go. Please review.

![cat](https://user-images.githubusercontent.com/314716/63757987-fa43ec00-c8b2-11e9-85e3-90aebecccc31.gif)

2019-08-27 09:33 UTC, eteq requested changes
Cats are great, but maybe that's not the best thing in your description but still :cat:!

Also, thanks for your contribution but it would be helpful if your PR title was a bit more descriptive. Additionally, the commit messages could be a bit more descriptive.  If you need some help on how to rebase, just ask.  I'm in the front of the room, with the white and blue and gray shirt. And long hair.

But regardless, we appreciate your hard, hard, hard work on this, and hope you will have a good look at my suggestions so we can merge it soon.

2019-08-27 09:33 UTC, eteq commented on Robitaille/template/README.md
> +>>>>> is_prime(5)
This is supposed to be three `>` - i.e. `>>>`.  Here's a suggestion:

```suggestion
>>> is_prime(5)
```

2019-08-27 09:33 UTC, eteq commented on Robitaille/template/README.md
> +There is a functon for finding prime Numbers:
I suggest using more consistent capitalization in your sentences.  Feel free to consult a style guide or ask a friendly collaborator. Like @eteq.  Hi friendly British person.  I like you.

2019-08-27 09:33 UTC, eteq commented on Robitaille/template/simple_functions.py
> +def IsPrime(value, option=None):
This is good to add, but it does not follow PEP8 Python style considerations.  (there are different style guides for Python versus Java, maybe you're more familiar with Java? Consider looking at [PEP8](https://www.python.org/dev/peps/pep-0008/).

At any rate, this is more consistent with our style guidelines:
```suggestion
def is_prime(value, option=None):
```

2019-08-27 09:33 UTC, eteq commented on Robitaille/template/simple_functions.py
> +    return value%2
Please use `format` instead of `%`.  That's our style suggestion.  Obviously this is a string not a number.  I know that, and so do you, right?

2019-08-27 09:33 UTC, eteq commented on Robitaille/template/buggy_function.py
> -    min_num = (hours_num - hours)*60
I'm lazy and didn't actually think that hard about what this does.  But can you confirm you really meant to delete this with no other replacement?

2019-08-28 09:26 UTC, closed without merging

2019-08-28 09:27 UTC, bsipocz commented
Thank you both for live demoing the process (and for the kittens), I'm closing this now.